### ISSUE TITLE
Mapswipe Workers Docker Restart Policy

### ISSUE THREAD

**Issue by Matthias-Schaub** [mapswipe/python-mapswipe-workers#223]
To avoid reaccuring errors and infinitly restarting container (and spamming Sentry), restarts of mapswipe workers container should be set to a maximum.

https://docs.docker.com/compose/compose-file/#restart_policy

What is the maximum? 5 times? Should we wait some time till restart?

```
restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
```
